apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
        - name:  webserver
          image: ahmet1162/webserver:1.0
          pullPolicy: IfNotPresent
          ports:
            - containerPort: 30001
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysql-dbname
                  key: db_name
                  
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password

            - name: MYSQL_DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: server-config
                  key: db_host
                  
